apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: server
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: env

