apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  replicas: 3
  template:
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/lootopia-org/server:latest
          command: ["/app/migrate"]
          envFrom:
            - configMapRef:
                name: app-config
      containers:
        - name: server
          envFrom:
            - configMapRef:
                name: app-config

