apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: server
          image: ghcr.io/lootopia-org/server:latest
          ports:
            - containerPort: 80
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: env          
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
      volumes:
        - name: env-file
          configMap:
            name: env
